# Generated by Django 3.2.6 on 2021-08-14 14:23

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CLC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField()),
                ('code_18', models.IntegerField()),
                ('shape_leng', models.FloatField()),
                ('shape_area', models.FloatField()),
                ('alternative_id', models.CharField(max_length=12)),
                ('area_ha', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=25832)),
            ],
        ),
    ]
